name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency: nope

jobs:
  build-installer:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            tar
          pacboy: >-
            7zip:p

      - name: Switch to the main mirror
        shell: msys2 {0}
        run: |
          echo 'Server = https://repo.msys2.org/mingw/$repo/' > /etc/pacman.d/mirrorlist.mingw
          echo 'Server = https://repo.msys2.org/msys/$arch/' > /etc/pacman.d/mirrorlist.msys
          pacman-conf.exe

      - name: Update using the main mirror & Check install
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
          msys2 -c 'pacman -Qkq'

      - name: Build Installer
        shell: msys2 {0}
        run: |
          bash make-msys2-installer

      - name: Create 'latest' Variants and Checksums
        run: |
          mv msys2-*.tar.zst msys2-base-x86_64-latest.tar.zst
          mv msys2-*.packages.txt msys2-base-x86_64-latest.packages.txt
          sha256sum.exe msys2-*
          sha256sum.exe msys2-* > msys2-checksums.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: msys2-*
